Print response body on  errors from mango test suite
Add `body` to error messages do error would look like

```
======================================================================
ERROR: test_group_field_number_is_unsupported (99-test_query.TestQuery.test_group_field_number_is_unsupported)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/Code/couchdb/src/mango/test/99-test_query.py", line 163, in test_group_field_number_is_unsupported
    self.db.create_text_index(name="animals")
  File "~/Code/couchdb/src/mango/test/mango.py", line 261, in create_text_index
    raise_for_status(r)
  File "~/Code/couchdb/src/mango/test/mango.py", line 102, in raise_for_status
    raise SearchException(err) from None
mango.SearchException: 503 Server Error: Service Unavailable for url: http://127.0.0.1:15984/mango_test_123c0654f1e84db7aed9d380062d8131/_index
request: {"index": {}, "type": "text", "w": 3, "name": "animals"}
response: {"error":"required index service unavailable","reason":"text"}
```