Explicit Python version in scripts
Recent Linux distributions start defaulting to Python 3, and require
ambiguous scripts to be more explicit.
For example building for Fedora 30 (not released yet) fails with:

    ERROR: ambiguous python shebang in /opt/couchdb/bin/couchup:
    #!/usr/bin/env python. Change it to python3 (or python2) explicitly.

So this commit changes the four Python scripts to use `python2`.

Note: They seem to be Python-3-compatible, but I couldn't be sure. If
you know they are, please tell me, I'll change it to `python3`.