Fix documentation to add package libkjsapi4
The current documentation doesn't ask to install package
libkjsapi4 as a dependency, which causes the following problem:

 Compiling /home/ubuntu/Devel/couchdb/src/couch/priv/couch_js/http.c
 /home/ubuntu/Devel/couchdb/src/couch/priv/couch_js/http.c:18:19: fatal error: jsapi.h: No such file or directory
  #include <jsapi.h>
                   ^
 compilation terminated.
 ERROR: compile failed while processing /home/ubuntu/Devel/couchdb/src/couch: rebar_abort
 Makefile:22: recipe for target 'couch' failed
 make: *** [couch] Error 1

This patch just fix the documentation and adds the package as a
dependency.